/*

 VIDA.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char vida[] =
{
  0x00,0x00,0x6C,0x6C,0x92,0xFE,0x82,0xFE,
  0x44,0x7C,0x28,0x38,0x10,0x10,0x00,0x00
};

/* End of VIDA.C */
