/*

 INIMIGO_TESTE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char inimigo[] =
{
  0x00,0x00,0x00,0x00,0x00,0x3C,0x28,0x56,
  0x28,0x56,0x00,0x7E,0x00,0x3C,0x6C,0x6C,
  0x00,0x00,0x00,0x00,0x00,0x3C,0x14,0x6A,
  0x14,0x6A,0x00,0x7E,0x00,0x3C,0x36,0x36
};

/* End of INIMIGO_TESTE.C */
