/*

 ESCOLHAS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\igor_\Documents\1 - UESC\Semestre 2\Linguagem de Programacao 2\Escape From UESC\gbdk\CRIAR SPRITE - gbtd22\Vista_Cima.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TorreWidth 20
#define TorreHeight 18
#define TorreBank 0

extern unsigned char Torre[];

/* End of ESCOLHAS.H */
