/*

 ESCAPE_FROM_UESC_1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 31 x 31
   Tile set      : Tiles_Mapa.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapamenuWidth 31
#define mapamenuHeight 31
#define mapamenuBank 0

extern unsigned char mapamenu[];

/* End of ESCAPE_FROM_UESC_1.H */
