/*

 ESCAPE_FROM_UESC_1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : C:\Users\igor_\Documents\1 - UESC\Semestre 2\Linguagem de Programacao 2\Jogo\Escape\Escape_From_UESC_1.7\Projeto\assets\background\Tiles_Mapa.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapa_bibliotecaWidth 32
#define mapa_bibliotecaHeight 18
#define mapa_bibliotecaBank 0

extern unsigned char mapa_biblioteca[];

/* End of ESCAPE_FROM_UESC_1.H */
