/*

 ESCAPE_FROM_UESC_1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\HD Documentos\1- UESC\Semestre 2\LinguagemDeProgramacao2\Jogo\Escape_From_UESC_1.5\Projeto\assets\fases\biblioteca\Biblioteca_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapa_bibliotecaWidth 20
#define mapa_bibliotecaHeight 18
#define mapa_bibliotecaBank 0

extern unsigned char mapa_biblioteca[];

/* End of ESCAPE_FROM_UESC_1.H */
